on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: validformbuilder/playground
        tags: latest
